--
-- Скрипт сгенерирован Devart dbForge Studio for MySQL, Версия 6.3.358.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/mysql/studio
-- Дата скрипта: 09.01.2016 0:11:55
-- Версия сервера: 5.5.46-0+deb8u1
-- Версия клиента: 4.1
--


-- 
-- Отключение внешних ключей
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Установить режим SQL (SQL mode)
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Установка кодировки, с использованием которой клиент будет посылать запросы на сервер
--
SET NAMES 'utf8';

-- 
-- Установка базы данных по умолчанию
--
USE inworkflow;

--
-- Описание для таблицы company
--
DROP TABLE IF EXISTS company;
CREATE TABLE company (
  id INT(11) NOT NULL AUTO_INCREMENT,
  account_name VARCHAR(50) NOT NULL,
  company_name VARCHAR(50) NOT NULL,
  url VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  timezone INT(11) DEFAULT NULL,
  active ENUM('Y','N') NOT NULL DEFAULT 'N',
  banned ENUM('Y','N') NOT NULL DEFAULT 'N',
  registered_at INT(11) NOT NULL,
  updated_at INT(11) NOT NULL,
  activate_code INT(8) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Описание для таблицы country
--
DROP TABLE IF EXISTS country;
CREATE TABLE country (
  id INT(11) NOT NULL AUTO_INCREMENT,
  country_code CHAR(2) DEFAULT NULL,
  country_name VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX idx_country_code (country_code)
)
ENGINE = MYISAM
AUTO_INCREMENT = 248
AVG_ROW_LENGTH = 25
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Описание для таблицы timezone
--
DROP TABLE IF EXISTS timezone;
CREATE TABLE timezone (
  id INT(10) NOT NULL AUTO_INCREMENT,
  country_code CHAR(2) NOT NULL,
  zone_name VARCHAR(35) NOT NULL,
  PRIMARY KEY (id),
  INDEX idx_zone_name (zone_name)
)
ENGINE = MYISAM
AUTO_INCREMENT = 418
AVG_ROW_LENGTH = 29
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Описание для таблицы users
--
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  company_id INT(11) DEFAULT NULL,
  name VARCHAR(50) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  passwd VARCHAR(255) DEFAULT NULL,
  timezone INT(11) DEFAULT 0,
  PRIMARY KEY (id),
  INDEX FK_users_company_id (company_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Вывод данных для таблицы company
--

-- Таблица inworkflow.company не содержит данных

-- 
-- Вывод данных для таблицы country
--
INSERT INTO country VALUES
(1, 'AF', 'Afghanistan'),
(2, 'AL', 'Albania'),
(3, 'DZ', 'Algeria'),
(4, 'AD', 'Andorra'),
(5, 'AO', 'Angola'),
(6, 'AG', 'Antigua and Barbuda'),
(7, 'AR', 'Argentina'),
(8, 'AM', 'Armenia'),
(9, 'AU', 'Australia'),
(10, 'AT', 'Austria'),
(11, 'AZ', 'Azerbaijan'),
(12, 'BS', 'Bahamas The'),
(13, 'BH', 'Bahrain'),
(14, 'BD', 'Bangladesh'),
(15, 'BB', 'Barbados'),
(16, 'BY', 'Belarus'),
(17, 'BE', 'Belgium'),
(18, 'BZ', 'Belize'),
(19, 'BJ', 'Benin'),
(20, 'BT', 'Bhutan'),
(21, 'BO', 'Bolivia'),
(22, 'BA', 'Bosnia and Herzegovina'),
(23, 'BW', 'Botswana'),
(24, 'BR', 'Brazil'),
(25, 'BN', 'Brunei'),
(26, 'BG', 'Bulgaria'),
(27, 'BF', 'Burkina Faso'),
(28, 'BI', 'Burundi'),
(29, 'KH', 'Cambodia'),
(30, 'CM', 'Cameroon'),
(31, 'CA', 'Canada'),
(32, 'CV', 'Cape Verde'),
(33, 'CF', 'Central African Republic'),
(34, 'TD', 'Chad'),
(35, 'CL', 'Chile'),
(36, 'CN', 'China Peoples Republic of'),
(37, 'CO', 'Colombia'),
(38, 'KM', 'Comoros'),
(39, 'CD', 'Congo Democratic Republic of the (Congo – Kin'),
(40, 'CG', 'Congo Republic of the (Congo – Brazzaville)'),
(41, 'CR', 'Costa Rica'),
(42, 'CI', 'Cote d''Ivoire (Ivory Coast)'),
(43, 'HR', 'Croatia'),
(44, 'CU', 'Cuba'),
(45, 'CY', 'Cyprus'),
(46, 'CZ', 'Czech Republic'),
(47, 'DK', 'Denmark'),
(48, 'DJ', 'Djibouti'),
(49, 'DM', 'Dominica'),
(50, 'DO', 'Dominican Republic'),
(51, 'EC', 'Ecuador'),
(52, 'EG', 'Egypt'),
(53, 'SV', 'El Salvador'),
(54, 'GQ', 'Equatorial Guinea'),
(55, 'ER', 'Eritrea'),
(56, 'EE', 'Estonia'),
(57, 'ET', 'Ethiopia'),
(58, 'FJ', 'Fiji'),
(59, 'FI', 'Finland'),
(60, 'FR', 'France'),
(61, 'GA', 'Gabon'),
(62, 'GM', 'Gambia The'),
(63, 'GE', 'Georgia'),
(64, 'DE', 'Germany'),
(65, 'GH', 'Ghana'),
(66, 'GR', 'Greece'),
(67, 'GD', 'Grenada'),
(68, 'GT', 'Guatemala'),
(69, 'GN', 'Guinea'),
(70, 'GW', 'Guinea-Bissau'),
(71, 'GY', 'Guyana'),
(72, 'HT', 'Haiti'),
(73, 'HN', 'Honduras'),
(74, 'HU', 'Hungary'),
(75, 'IS', 'Iceland'),
(76, 'IN', 'India'),
(77, 'ID', 'Indonesia'),
(78, 'IR', 'Iran'),
(79, 'IQ', 'Iraq'),
(80, 'IE', 'Ireland'),
(81, 'IL', 'Israel'),
(82, 'IT', 'Italy'),
(83, 'JM', 'Jamaica'),
(84, 'JP', 'Japan'),
(85, 'JO', 'Jordan'),
(86, 'KZ', 'Kazakhstan'),
(87, 'KE', 'Kenya'),
(88, 'KI', 'Kiribati'),
(89, 'KP', 'Korea Democratic Peoples Republic of (North K'),
(90, 'KR', 'Korea, Republic of  (South Korea)'),
(91, 'KW', 'Kuwait'),
(92, 'KG', 'Kyrgyzstan'),
(93, 'LA', 'Laos'),
(94, 'LV', 'Latvia'),
(95, 'LB', 'Lebanon'),
(96, 'LS', 'Lesotho'),
(97, 'LR', 'Liberia'),
(98, 'LY', 'Libya'),
(99, 'LI', 'Liechtenstein'),
(100, 'LT', 'Lithuania'),
(101, 'LU', 'Luxembourg'),
(102, 'MK', 'Macedonia'),
(103, 'MG', 'Madagascar'),
(104, 'MW', 'Malawi'),
(105, 'MY', 'Malaysia'),
(106, 'MV', 'Maldives'),
(107, 'ML', 'Mali'),
(108, 'MT', 'Malta'),
(109, 'MH', 'Marshall Islands'),
(110, 'MR', 'Mauritania'),
(111, 'MU', 'Mauritius'),
(112, 'MX', 'Mexico'),
(113, 'FM', 'Micronesia'),
(114, 'MD', 'Moldova'),
(115, 'MC', 'Monaco'),
(116, 'MN', 'Mongolia'),
(117, NULL, 'Montenegro'),
(118, 'MA', 'Morocco'),
(119, 'MZ', 'Mozambique'),
(120, 'MM', 'Myanmar (Burma)'),
(121, 'NA', 'Namibia'),
(122, 'NR', 'Nauru'),
(123, 'NP', 'Nepal'),
(124, 'NL', 'Netherlands'),
(125, 'NZ', 'New Zealand'),
(126, 'NI', 'Nicaragua'),
(127, 'NE', 'Niger'),
(128, 'NG', 'Nigeria'),
(129, 'NO', 'Norway'),
(130, 'OM', 'Oman'),
(131, 'PK', 'Pakistan'),
(132, 'PW', 'Palau'),
(133, 'PA', 'Panama'),
(134, 'PG', 'Papua New Guinea'),
(135, 'PY', 'Paraguay'),
(136, 'PE', 'Peru'),
(137, 'PH', 'Philippines'),
(138, 'PL', 'Poland'),
(139, 'PT', 'Portugal'),
(140, 'QA', 'Qatar'),
(141, 'RO', 'Romania'),
(142, 'RU', 'Russia'),
(143, 'RW', 'Rwanda'),
(144, 'KN', 'Saint Kitts and Nevis'),
(145, 'LC', 'Saint Lucia'),
(146, 'VC', 'Saint Vincent and the Grenadines'),
(147, 'WS', 'Samoa'),
(148, 'SM', 'San Marino'),
(149, 'ST', 'Sao Tome and Principe'),
(150, 'SA', 'Saudi Arabia'),
(151, 'SN', 'Senegal'),
(152, NULL, 'Serbia'),
(153, 'SC', 'Seychelles'),
(154, 'SL', 'Sierra Leone'),
(155, 'SG', 'Singapore'),
(156, 'SK', 'Slovakia'),
(157, 'SI', 'Slovenia'),
(158, 'SB', 'Solomon Islands'),
(159, 'SO', 'Somalia'),
(160, 'ZA', 'South Africa'),
(161, 'ES', 'Spain'),
(162, 'LK', 'Sri Lanka'),
(163, 'SD', 'Sudan'),
(164, 'SR', 'Suriname'),
(165, 'SZ', 'Swaziland'),
(166, 'SE', 'Sweden'),
(167, 'CH', 'Switzerland'),
(168, 'SY', 'Syria'),
(169, 'TJ', 'Tajikistan'),
(170, 'TZ', 'Tanzania'),
(171, 'TH', 'Thailand'),
(172, 'TL', 'Timor-Leste (East Timor)'),
(173, 'TG', 'Togo'),
(174, 'TO', 'Tonga'),
(175, 'TT', 'Trinidad and Tobago'),
(176, 'TN', 'Tunisia'),
(177, 'TR', 'Turkey'),
(178, 'TM', 'Turkmenistan'),
(179, 'TV', 'Tuvalu'),
(180, 'UG', 'Uganda'),
(181, 'UA', 'Ukraine'),
(182, 'AE', 'United Arab Emirates'),
(183, 'GB', 'United Kingdom'),
(184, 'US', 'United States'),
(185, 'UY', 'Uruguay'),
(186, 'UZ', 'Uzbekistan'),
(187, 'VU', 'Vanuatu'),
(188, 'VA', 'Vatican City'),
(189, 'VE', 'Venezuela'),
(190, 'VN', 'Vietnam'),
(191, 'YE', 'Yemen'),
(192, 'ZM', 'Zambia'),
(193, 'ZW', 'Zimbabwe'),
(194, 'GS', 'South Georgia and the South Sandwich Islands'),
(195, 'AX', 'Åland Islands'),
(196, 'SJ', 'Svalbard and Jan Mayen'),
(197, 'TF', 'French Southern Lands'),
(198, 'PF', 'French Polynesia'),
(199, 'GF', 'French Guiana'),
(200, 'FK', 'Falkland Islands (Islas Malvinas)'),
(201, 'FO', 'Faroe Islands'),
(202, 'WF', 'Wallis and Futuna'),
(203, 'TK', 'Tokelau'),
(204, 'TW', 'Taiwan'),
(205, 'PM', 'Saint Pierre and Miquelon'),
(206, 'BL', 'Saint Barthélemy'),
(207, 'MP', 'Northern Mariana Islands'),
(208, 'SH', 'Saint Helena'),
(209, 'RE', 'Reunion'),
(210, 'PR', 'Puerto Rico'),
(211, 'PN', 'Pitcairn'),
(212, 'PS', 'Palestinian Territory, Occupied'),
(213, 'TC', 'Turks and Caicos Islands'),
(214, 'CK', 'Cook Islands'),
(215, 'KY', 'Cayman Islands'),
(216, 'HM', 'Heard Island and McDonald Islands'),
(217, 'MF', 'Saint Martin'),
(218, 'CX', 'Christmas Island'),
(219, 'NF', 'Norfolk Island'),
(220, 'BV', 'Bouvet Island'),
(221, 'NC', 'New Caledonia'),
(222, 'NU', 'Niue'),
(223, 'AN', 'Netherlands Antilles'),
(224, 'MS', 'Montserrat'),
(225, 'MQ', 'Martinique'),
(226, 'UM', 'United States Pacific Island Wildlife Refuges'),
(227, 'IM', 'Isle of Man'),
(228, 'YT', 'Mayotte'),
(229, 'MO', 'Macau'),
(230, '', 'Kosovo'),
(231, 'CC', 'Cocos (Keeling) Islands'),
(232, 'EH', 'Western Sahara'),
(233, 'GU', 'Guam'),
(234, 'JE', 'Jersey'),
(235, 'GL', 'Greenland'),
(236, 'HK', 'Hong Kong'),
(237, 'GI', 'Gibraltar'),
(238, 'GG', 'Guernsey'),
(239, 'GP', 'Guadeloupe'),
(240, 'VI', 'Virgin Islands'),
(241, 'VG', 'British Virgin Islands'),
(242, 'IO', 'British Indian Ocean Territory'),
(243, 'BM', 'Bermuda'),
(244, 'AW', 'Aruba'),
(245, 'AQ', 'Antarctica'),
(246, 'AI', 'Anguilla'),
(247, 'AS', 'American Samoa');

-- 
-- Вывод данных для таблицы timezone
--
INSERT INTO timezone VALUES
(1, 'AD', 'Europe/Andorra'),
(2, 'AE', 'Asia/Dubai'),
(3, 'AF', 'Asia/Kabul'),
(4, 'AG', 'America/Antigua'),
(5, 'AI', 'America/Anguilla'),
(6, 'AL', 'Europe/Tirane'),
(7, 'AM', 'Asia/Yerevan'),
(8, 'AO', 'Africa/Luanda'),
(9, 'AQ', 'Antarctica/McMurdo'),
(10, 'AQ', 'Antarctica/Rothera'),
(11, 'AQ', 'Antarctica/Palmer'),
(12, 'AQ', 'Antarctica/Mawson'),
(13, 'AQ', 'Antarctica/Davis'),
(14, 'AQ', 'Antarctica/Casey'),
(15, 'AQ', 'Antarctica/Vostok'),
(16, 'AQ', 'Antarctica/DumontDUrville'),
(17, 'AQ', 'Antarctica/Syowa'),
(18, 'AQ', 'Antarctica/Troll'),
(19, 'AR', 'America/Argentina/Buenos_Aires'),
(20, 'AR', 'America/Argentina/Cordoba'),
(21, 'AR', 'America/Argentina/Salta'),
(22, 'AR', 'America/Argentina/Jujuy'),
(23, 'AR', 'America/Argentina/Tucuman'),
(24, 'AR', 'America/Argentina/Catamarca'),
(25, 'AR', 'America/Argentina/La_Rioja'),
(26, 'AR', 'America/Argentina/San_Juan'),
(27, 'AR', 'America/Argentina/Mendoza'),
(28, 'AR', 'America/Argentina/San_Luis'),
(29, 'AR', 'America/Argentina/Rio_Gallegos'),
(30, 'AR', 'America/Argentina/Ushuaia'),
(31, 'AS', 'Pacific/Pago_Pago'),
(32, 'AT', 'Europe/Vienna'),
(33, 'AU', 'Australia/Lord_Howe'),
(34, 'AU', 'Antarctica/Macquarie'),
(35, 'AU', 'Australia/Hobart'),
(36, 'AU', 'Australia/Currie'),
(37, 'AU', 'Australia/Melbourne'),
(38, 'AU', 'Australia/Sydney'),
(39, 'AU', 'Australia/Broken_Hill'),
(40, 'AU', 'Australia/Brisbane'),
(41, 'AU', 'Australia/Lindeman'),
(42, 'AU', 'Australia/Adelaide'),
(43, 'AU', 'Australia/Darwin'),
(44, 'AU', 'Australia/Perth'),
(45, 'AU', 'Australia/Eucla'),
(46, 'AW', 'America/Aruba'),
(47, 'AX', 'Europe/Mariehamn'),
(48, 'AZ', 'Asia/Baku'),
(49, 'BA', 'Europe/Sarajevo'),
(50, 'BB', 'America/Barbados'),
(51, 'BD', 'Asia/Dhaka'),
(52, 'BE', 'Europe/Brussels'),
(53, 'BF', 'Africa/Ouagadougou'),
(54, 'BG', 'Europe/Sofia'),
(55, 'BH', 'Asia/Bahrain'),
(56, 'BI', 'Africa/Bujumbura'),
(57, 'BJ', 'Africa/Porto-Novo'),
(58, 'BL', 'America/St_Barthelemy'),
(59, 'BM', 'Atlantic/Bermuda'),
(60, 'BN', 'Asia/Brunei'),
(61, 'BO', 'America/La_Paz'),
(62, 'BQ', 'America/Kralendijk'),
(63, 'BR', 'America/Noronha'),
(64, 'BR', 'America/Belem'),
(65, 'BR', 'America/Fortaleza'),
(66, 'BR', 'America/Recife'),
(67, 'BR', 'America/Araguaina'),
(68, 'BR', 'America/Maceio'),
(69, 'BR', 'America/Bahia'),
(70, 'BR', 'America/Sao_Paulo'),
(71, 'BR', 'America/Campo_Grande'),
(72, 'BR', 'America/Cuiaba'),
(73, 'BR', 'America/Santarem'),
(74, 'BR', 'America/Porto_Velho'),
(75, 'BR', 'America/Boa_Vista'),
(76, 'BR', 'America/Manaus'),
(77, 'BR', 'America/Eirunepe'),
(78, 'BR', 'America/Rio_Branco'),
(79, 'BS', 'America/Nassau'),
(80, 'BT', 'Asia/Thimphu'),
(81, 'BW', 'Africa/Gaborone'),
(82, 'BY', 'Europe/Minsk'),
(83, 'BZ', 'America/Belize'),
(84, 'CA', 'America/St_Johns'),
(85, 'CA', 'America/Halifax'),
(86, 'CA', 'America/Glace_Bay'),
(87, 'CA', 'America/Moncton'),
(88, 'CA', 'America/Goose_Bay'),
(89, 'CA', 'America/Blanc-Sablon'),
(90, 'CA', 'America/Toronto'),
(91, 'CA', 'America/Nipigon'),
(92, 'CA', 'America/Thunder_Bay'),
(93, 'CA', 'America/Iqaluit'),
(94, 'CA', 'America/Pangnirtung'),
(95, 'CA', 'America/Resolute'),
(96, 'CA', 'America/Atikokan'),
(97, 'CA', 'America/Rankin_Inlet'),
(98, 'CA', 'America/Winnipeg'),
(99, 'CA', 'America/Rainy_River'),
(100, 'CA', 'America/Regina'),
(101, 'CA', 'America/Swift_Current'),
(102, 'CA', 'America/Edmonton'),
(103, 'CA', 'America/Cambridge_Bay'),
(104, 'CA', 'America/Yellowknife'),
(105, 'CA', 'America/Inuvik'),
(106, 'CA', 'America/Creston'),
(107, 'CA', 'America/Dawson_Creek'),
(108, 'CA', 'America/Fort_Nelson'),
(109, 'CA', 'America/Vancouver'),
(110, 'CA', 'America/Whitehorse'),
(111, 'CA', 'America/Dawson'),
(112, 'CC', 'Indian/Cocos'),
(113, 'CD', 'Africa/Kinshasa'),
(114, 'CD', 'Africa/Lubumbashi'),
(115, 'CF', 'Africa/Bangui'),
(116, 'CG', 'Africa/Brazzaville'),
(117, 'CH', 'Europe/Zurich'),
(118, 'CI', 'Africa/Abidjan'),
(119, 'CK', 'Pacific/Rarotonga'),
(120, 'CL', 'America/Santiago'),
(121, 'CL', 'Pacific/Easter'),
(122, 'CM', 'Africa/Douala'),
(123, 'CN', 'Asia/Shanghai'),
(124, 'CN', 'Asia/Urumqi'),
(125, 'CO', 'America/Bogota'),
(126, 'CR', 'America/Costa_Rica'),
(127, 'CU', 'America/Havana'),
(128, 'CV', 'Atlantic/Cape_Verde'),
(129, 'CW', 'America/Curacao'),
(130, 'CX', 'Indian/Christmas'),
(131, 'CY', 'Asia/Nicosia'),
(132, 'CZ', 'Europe/Prague'),
(133, 'DE', 'Europe/Berlin'),
(134, 'DE', 'Europe/Busingen'),
(135, 'DJ', 'Africa/Djibouti'),
(136, 'DK', 'Europe/Copenhagen'),
(137, 'DM', 'America/Dominica'),
(138, 'DO', 'America/Santo_Domingo'),
(139, 'DZ', 'Africa/Algiers'),
(140, 'EC', 'America/Guayaquil'),
(141, 'EC', 'Pacific/Galapagos'),
(142, 'EE', 'Europe/Tallinn'),
(143, 'EG', 'Africa/Cairo'),
(144, 'EH', 'Africa/El_Aaiun'),
(145, 'ER', 'Africa/Asmara'),
(146, 'ES', 'Europe/Madrid'),
(147, 'ES', 'Africa/Ceuta'),
(148, 'ES', 'Atlantic/Canary'),
(149, 'ET', 'Africa/Addis_Ababa'),
(150, 'FI', 'Europe/Helsinki'),
(151, 'FJ', 'Pacific/Fiji'),
(152, 'FK', 'Atlantic/Stanley'),
(153, 'FM', 'Pacific/Chuuk'),
(154, 'FM', 'Pacific/Pohnpei'),
(155, 'FM', 'Pacific/Kosrae'),
(156, 'FO', 'Atlantic/Faroe'),
(157, 'FR', 'Europe/Paris'),
(158, 'GA', 'Africa/Libreville'),
(159, 'GB', 'Europe/London'),
(160, 'GD', 'America/Grenada'),
(161, 'GE', 'Asia/Tbilisi'),
(162, 'GF', 'America/Cayenne'),
(163, 'GG', 'Europe/Guernsey'),
(164, 'GH', 'Africa/Accra'),
(165, 'GI', 'Europe/Gibraltar'),
(166, 'GL', 'America/Godthab'),
(167, 'GL', 'America/Danmarkshavn'),
(168, 'GL', 'America/Scoresbysund'),
(169, 'GL', 'America/Thule'),
(170, 'GM', 'Africa/Banjul'),
(171, 'GN', 'Africa/Conakry'),
(172, 'GP', 'America/Guadeloupe'),
(173, 'GQ', 'Africa/Malabo'),
(174, 'GR', 'Europe/Athens'),
(175, 'GS', 'Atlantic/South_Georgia'),
(176, 'GT', 'America/Guatemala'),
(177, 'GU', 'Pacific/Guam'),
(178, 'GW', 'Africa/Bissau'),
(179, 'GY', 'America/Guyana'),
(180, 'HK', 'Asia/Hong_Kong'),
(181, 'HN', 'America/Tegucigalpa'),
(182, 'HR', 'Europe/Zagreb'),
(183, 'HT', 'America/Port-au-Prince'),
(184, 'HU', 'Europe/Budapest'),
(185, 'ID', 'Asia/Jakarta'),
(186, 'ID', 'Asia/Pontianak'),
(187, 'ID', 'Asia/Makassar'),
(188, 'ID', 'Asia/Jayapura'),
(189, 'IE', 'Europe/Dublin'),
(190, 'IL', 'Asia/Jerusalem'),
(191, 'IM', 'Europe/Isle_of_Man'),
(192, 'IN', 'Asia/Kolkata'),
(193, 'IO', 'Indian/Chagos'),
(194, 'IQ', 'Asia/Baghdad'),
(195, 'IR', 'Asia/Tehran'),
(196, 'IS', 'Atlantic/Reykjavik'),
(197, 'IT', 'Europe/Rome'),
(198, 'JE', 'Europe/Jersey'),
(199, 'JM', 'America/Jamaica'),
(200, 'JO', 'Asia/Amman'),
(201, 'JP', 'Asia/Tokyo'),
(202, 'KE', 'Africa/Nairobi'),
(203, 'KG', 'Asia/Bishkek'),
(204, 'KH', 'Asia/Phnom_Penh'),
(205, 'KI', 'Pacific/Tarawa'),
(206, 'KI', 'Pacific/Enderbury'),
(207, 'KI', 'Pacific/Kiritimati'),
(208, 'KM', 'Indian/Comoro'),
(209, 'KN', 'America/St_Kitts'),
(210, 'KP', 'Asia/Pyongyang'),
(211, 'KR', 'Asia/Seoul'),
(212, 'KW', 'Asia/Kuwait'),
(213, 'KY', 'America/Cayman'),
(214, 'KZ', 'Asia/Almaty'),
(215, 'KZ', 'Asia/Qyzylorda'),
(216, 'KZ', 'Asia/Aqtobe'),
(217, 'KZ', 'Asia/Aqtau'),
(218, 'KZ', 'Asia/Oral'),
(219, 'LA', 'Asia/Vientiane'),
(220, 'LB', 'Asia/Beirut'),
(221, 'LC', 'America/St_Lucia'),
(222, 'LI', 'Europe/Vaduz'),
(223, 'LK', 'Asia/Colombo'),
(224, 'LR', 'Africa/Monrovia'),
(225, 'LS', 'Africa/Maseru'),
(226, 'LT', 'Europe/Vilnius'),
(227, 'LU', 'Europe/Luxembourg'),
(228, 'LV', 'Europe/Riga'),
(229, 'LY', 'Africa/Tripoli'),
(230, 'MA', 'Africa/Casablanca'),
(231, 'MC', 'Europe/Monaco'),
(232, 'MD', 'Europe/Chisinau'),
(233, 'ME', 'Europe/Podgorica'),
(234, 'MF', 'America/Marigot'),
(235, 'MG', 'Indian/Antananarivo'),
(236, 'MH', 'Pacific/Majuro'),
(237, 'MH', 'Pacific/Kwajalein'),
(238, 'MK', 'Europe/Skopje'),
(239, 'ML', 'Africa/Bamako'),
(240, 'MM', 'Asia/Rangoon'),
(241, 'MN', 'Asia/Ulaanbaatar'),
(242, 'MN', 'Asia/Hovd'),
(243, 'MN', 'Asia/Choibalsan'),
(244, 'MO', 'Asia/Macau'),
(245, 'MP', 'Pacific/Saipan'),
(246, 'MQ', 'America/Martinique'),
(247, 'MR', 'Africa/Nouakchott'),
(248, 'MS', 'America/Montserrat'),
(249, 'MT', 'Europe/Malta'),
(250, 'MU', 'Indian/Mauritius'),
(251, 'MV', 'Indian/Maldives'),
(252, 'MW', 'Africa/Blantyre'),
(253, 'MX', 'America/Mexico_City'),
(254, 'MX', 'America/Cancun'),
(255, 'MX', 'America/Merida'),
(256, 'MX', 'America/Monterrey'),
(257, 'MX', 'America/Matamoros'),
(258, 'MX', 'America/Mazatlan'),
(259, 'MX', 'America/Chihuahua'),
(260, 'MX', 'America/Ojinaga'),
(261, 'MX', 'America/Hermosillo'),
(262, 'MX', 'America/Tijuana'),
(263, 'MX', 'America/Santa_Isabel'),
(264, 'MX', 'America/Bahia_Banderas'),
(265, 'MY', 'Asia/Kuala_Lumpur'),
(266, 'MY', 'Asia/Kuching'),
(267, 'MZ', 'Africa/Maputo'),
(268, 'NA', 'Africa/Windhoek'),
(269, 'NC', 'Pacific/Noumea'),
(270, 'NE', 'Africa/Niamey'),
(271, 'NF', 'Pacific/Norfolk'),
(272, 'NG', 'Africa/Lagos'),
(273, 'NI', 'America/Managua'),
(274, 'NL', 'Europe/Amsterdam'),
(275, 'NO', 'Europe/Oslo'),
(276, 'NP', 'Asia/Kathmandu'),
(277, 'NR', 'Pacific/Nauru'),
(278, 'NU', 'Pacific/Niue'),
(279, 'NZ', 'Pacific/Auckland'),
(280, 'NZ', 'Pacific/Chatham'),
(281, 'OM', 'Asia/Muscat'),
(282, 'PA', 'America/Panama'),
(283, 'PE', 'America/Lima'),
(284, 'PF', 'Pacific/Tahiti'),
(285, 'PF', 'Pacific/Marquesas'),
(286, 'PF', 'Pacific/Gambier'),
(287, 'PG', 'Pacific/Port_Moresby'),
(288, 'PG', 'Pacific/Bougainville'),
(289, 'PH', 'Asia/Manila'),
(290, 'PK', 'Asia/Karachi'),
(291, 'PL', 'Europe/Warsaw'),
(292, 'PM', 'America/Miquelon'),
(293, 'PN', 'Pacific/Pitcairn'),
(294, 'PR', 'America/Puerto_Rico'),
(295, 'PS', 'Asia/Gaza'),
(296, 'PS', 'Asia/Hebron'),
(297, 'PT', 'Europe/Lisbon'),
(298, 'PT', 'Atlantic/Madeira'),
(299, 'PT', 'Atlantic/Azores'),
(300, 'PW', 'Pacific/Palau'),
(301, 'PY', 'America/Asuncion'),
(302, 'QA', 'Asia/Qatar'),
(303, 'RE', 'Indian/Reunion'),
(304, 'RO', 'Europe/Bucharest'),
(305, 'RS', 'Europe/Belgrade'),
(306, 'RU', 'Europe/Kaliningrad'),
(307, 'RU', 'Europe/Moscow'),
(308, 'RU', 'Europe/Simferopol'),
(309, 'RU', 'Europe/Volgograd'),
(310, 'RU', 'Europe/Samara'),
(311, 'RU', 'Asia/Yekaterinburg'),
(312, 'RU', 'Asia/Omsk'),
(313, 'RU', 'Asia/Novosibirsk'),
(314, 'RU', 'Asia/Novokuznetsk'),
(315, 'RU', 'Asia/Krasnoyarsk'),
(316, 'RU', 'Asia/Irkutsk'),
(317, 'RU', 'Asia/Chita'),
(318, 'RU', 'Asia/Yakutsk'),
(319, 'RU', 'Asia/Khandyga'),
(320, 'RU', 'Asia/Vladivostok'),
(321, 'RU', 'Asia/Sakhalin'),
(322, 'RU', 'Asia/Ust-Nera'),
(323, 'RU', 'Asia/Magadan'),
(324, 'RU', 'Asia/Srednekolymsk'),
(325, 'RU', 'Asia/Kamchatka'),
(326, 'RU', 'Asia/Anadyr'),
(327, 'RW', 'Africa/Kigali'),
(328, 'SA', 'Asia/Riyadh'),
(329, 'SB', 'Pacific/Guadalcanal'),
(330, 'SC', 'Indian/Mahe'),
(331, 'SD', 'Africa/Khartoum'),
(332, 'SE', 'Europe/Stockholm'),
(333, 'SG', 'Asia/Singapore'),
(334, 'SH', 'Atlantic/St_Helena'),
(335, 'SI', 'Europe/Ljubljana'),
(336, 'SJ', 'Arctic/Longyearbyen'),
(337, 'SK', 'Europe/Bratislava'),
(338, 'SL', 'Africa/Freetown'),
(339, 'SM', 'Europe/San_Marino'),
(340, 'SN', 'Africa/Dakar'),
(341, 'SO', 'Africa/Mogadishu'),
(342, 'SR', 'America/Paramaribo'),
(343, 'SS', 'Africa/Juba'),
(344, 'ST', 'Africa/Sao_Tome'),
(345, 'SV', 'America/El_Salvador'),
(346, 'SX', 'America/Lower_Princes'),
(347, 'SY', 'Asia/Damascus'),
(348, 'SZ', 'Africa/Mbabane'),
(349, 'TC', 'America/Grand_Turk'),
(350, 'TD', 'Africa/Ndjamena'),
(351, 'TF', 'Indian/Kerguelen'),
(352, 'TG', 'Africa/Lome'),
(353, 'TH', 'Asia/Bangkok'),
(354, 'TJ', 'Asia/Dushanbe'),
(355, 'TK', 'Pacific/Fakaofo'),
(356, 'TL', 'Asia/Dili'),
(357, 'TM', 'Asia/Ashgabat'),
(358, 'TN', 'Africa/Tunis'),
(359, 'TO', 'Pacific/Tongatapu'),
(360, 'TR', 'Europe/Istanbul'),
(361, 'TT', 'America/Port_of_Spain'),
(362, 'TV', 'Pacific/Funafuti'),
(363, 'TW', 'Asia/Taipei'),
(364, 'TZ', 'Africa/Dar_es_Salaam'),
(365, 'UA', 'Europe/Kiev'),
(366, 'UA', 'Europe/Uzhgorod'),
(367, 'UA', 'Europe/Zaporozhye'),
(368, 'UG', 'Africa/Kampala'),
(369, 'UM', 'Pacific/Johnston'),
(370, 'UM', 'Pacific/Midway'),
(371, 'UM', 'Pacific/Wake'),
(372, 'US', 'America/New_York'),
(373, 'US', 'America/Detroit'),
(374, 'US', 'America/Kentucky/Louisville'),
(375, 'US', 'America/Kentucky/Monticello'),
(376, 'US', 'America/Indiana/Indianapolis'),
(377, 'US', 'America/Indiana/Vincennes'),
(378, 'US', 'America/Indiana/Winamac'),
(379, 'US', 'America/Indiana/Marengo'),
(380, 'US', 'America/Indiana/Petersburg'),
(381, 'US', 'America/Indiana/Vevay'),
(382, 'US', 'America/Chicago'),
(383, 'US', 'America/Indiana/Tell_City'),
(384, 'US', 'America/Indiana/Knox'),
(385, 'US', 'America/Menominee'),
(386, 'US', 'America/North_Dakota/Center'),
(387, 'US', 'America/North_Dakota/New_Salem'),
(388, 'US', 'America/North_Dakota/Beulah'),
(389, 'US', 'America/Denver'),
(390, 'US', 'America/Boise'),
(391, 'US', 'America/Phoenix'),
(392, 'US', 'America/Los_Angeles'),
(393, 'US', 'America/Metlakatla'),
(394, 'US', 'America/Anchorage'),
(395, 'US', 'America/Juneau'),
(396, 'US', 'America/Sitka'),
(397, 'US', 'America/Yakutat'),
(398, 'US', 'America/Nome'),
(399, 'US', 'America/Adak'),
(400, 'US', 'Pacific/Honolulu'),
(401, 'UY', 'America/Montevideo'),
(402, 'UZ', 'Asia/Samarkand'),
(403, 'UZ', 'Asia/Tashkent'),
(404, 'VA', 'Europe/Vatican'),
(405, 'VC', 'America/St_Vincent'),
(406, 'VE', 'America/Caracas'),
(407, 'VG', 'America/Tortola'),
(408, 'VI', 'America/St_Thomas'),
(409, 'VN', 'Asia/Ho_Chi_Minh'),
(410, 'VU', 'Pacific/Efate'),
(411, 'WF', 'Pacific/Wallis'),
(412, 'WS', 'Pacific/Apia'),
(413, 'YE', 'Asia/Aden'),
(414, 'YT', 'Indian/Mayotte'),
(415, 'ZA', 'Africa/Johannesburg'),
(416, 'ZM', 'Africa/Lusaka'),
(417, 'ZW', 'Africa/Harare');

-- 
-- Вывод данных для таблицы users
--

-- Таблица inworkflow.users не содержит данных

-- 
-- Восстановить предыдущий режим SQL (SQL mode)
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Включение внешних ключей
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;